server:
  port: 8300
spring:
  mvc:
    async:
      request-timeout: 5000
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: quick-user
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
  profiles:
    active: dev

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    # 让feign使用apache httpclient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

#配置mybatis参数
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  # 忽略sentinel的排查
  health:
    sentinel:
      enabled: false