spring:
  datasource:
    url: jdbc:oracle:thin:@${server-ip}:1521/helowin
    username: htd
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    database: 0
    host: ${server-ip}  #单机
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
minio:
  url: ${http}${server-ip}
  port: ${minio-port}
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: quick
  bace_url: ${http}${server-ip}:${minio-port}/

