spring:
  application:
    name: quick-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 1.14.153.121:8848
        cluster-name: quick
  security:
    user:
      name: admin
      password: admin
  redis:
    database: 0
    host: 1.14.153.121  #单机
    port: 6379
    timeout: 200
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

feign:
  sentinel:

    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    # 让feign使用apache httpclient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
quick:
  monitor-phones: 13616770113



# 日志
logging:
  config: classpath:logback-monitor.xml
