spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/HUTONGDA
    username: hutongda
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: quick-inner
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: wz
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
        #        transport:
        # 指定sentinel 控制台的地址
  #          dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 10.11.82.75  #单机
    port: 6379
    #    sentinel:
    #      master: mymaster
    #      nodes: 10.11.82.74:26379,10.11.82.71:26379,10.11.82.72:26379
    password: Wzmtr123456
    timeout: 200
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
feign:
  sentinel:

    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    # 让feign使用apache httpclient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#配置mybatis参数
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

fdfs:
  connect-timeout: 600
  so-timeout: 2500
  thumb-image:
    height: 60
    width: 60
  pool:
    max-total: 300
    max-total-per-key: 300
    max-wait-millis: 5000
  tracker-list:
    - 10.11.82.75:22122
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
