spring:
  datasource:
    url: jdbc:oracle:thin:@1.14.153.121:1521/helowin
    username: htd
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: quick-user
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 1.14.153.121  #单机
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    # 让feign使用apache httpclient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#配置mybatis参数
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

minio:
  url: http://1.14.153.121
  port: 9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: quick
  bace_url: http://1.14.153.121:9000/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  # 忽略sentinel的排查
#  health:
#    sentinel:
#      enabled: false
